import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

// const poppins = Poppins({ subsets: ['latin-ext'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-blue-900 to-blue-500 w-screen h-screen top-0 left-0">
        <Header />

        {children}
      </body>
    </html>
  );
}
